---
- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
    enabled: true

- name: GRUB update
  ansible.builtin.command: grub-mkconfig -o /boot/grub/grub.cfg

- name: Apply sysctl values
  ansible.builtin.command: sysctl --system
