---
- name: Installation of required packages
  ansible.builtin.apt:
    pkg:
    - mariadb-server
    - python3-mysqldb

- name: Start and enable the mariadb service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Add the mariadb.cnf
  ansible.builtin.copy:
    src: ../templates/50-server.cnf
    dest: /etc/mysql/mariadb.conf.d/
    owner: root
    group: root
    mode: '0644'
  notify: Restart mariadb

- name: Add the mariadb.cnf
  ansible.builtin.copy:
    src: ../templates/mariadb.cnf
    dest: /etc/mysql/conf.d/
    owner: root
    group: root
    mode: '0644'
  notify: Restart mariadb

- name: Add the CA for MariaDB
  ansible.builtin.copy:
    src: ../secrets/ca.pem
    dest: /etc/ssl/certs/ca-exoindustries.pem
    owner: root
    group: root
    mode: "0644"
  notify: Restart mariadb

- name: Add the TLS cert for MariaDB
  ansible.builtin.copy:
    src: ../secrets/mariadb.exo-industries.xyz.crt
    dest: /etc/ssl/certs/glpi.exo-industries.xyz.crt
    owner: root
    group: root
    mode: "0640"
  notify: Restart mariadb

- name: Add the TLS key for MariaDB
  ansible.builtin.copy:
    src: ../secrets/mariadb.exo-industries.xyz.key
    dest: /etc/ssl/private/mariadb.exo-industries.xyz.key
    owner: root
    group: root
    mode: "0600"
  notify: Restart mariadb

- name: Delete default databases
  mysql_db:
    name: sys
    state: absent

- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
