---
- name: Installation of packages
  ansible.builtin.apt:
    pkg:
    - haproxy
    - certbot

- name: Start and enable the HAproxy service
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: true

- name: Installation of the HAproxy configuration
  ansible.builtin.template:
    src: ../templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
  notify: Restart haproxy
