---
- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true

- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
    enabled: true

- name: Restart php-fpm
  ansible.builtin.service:
    name: php{{ php_version }}-fpm
    state: restarted
    enabled: true
