---
- name: Installation of bind9
  ansible.builtin.apt:
    pkg:
    - bind9
    - bind9-utils

- name: Installation of named.conf.local
  ansible.builtin.template:
    src: ../templates/named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: '0644'
  notify:
    - Restart bind9

- name: Installation of named.conf.options
  ansible.builtin.template:
    src: ../templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: '0644'
  notify:
    - Restart bind9
