---
- name: Installation of the pmonit configuration
  ansible.builtin.copy:
    src: pmonit
    dest: /etc/nginx/sites-available/
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx

- name: Activation of the pmonit website
  ansible.builtin.file:
    src: /etc/nginx/sites-available/pmonit
    dest: /etc/nginx/sites-enabled/pmonit
    owner: root
    group: root
    state: link
  notify: Reload nginx

- name: Add the TLS cert for pmonit
  ansible.builtin.copy:
    src: pmonit.exo-industries.xyz.crt
    dest: /etc/ssl/certs/
    owner: root
    group: root
    mode: "0640"
  notify: Restart nginx

- name: Add the TLS key for pmonit
  ansible.builtin.copy:
    src: pmonit.exo-industries.xyz.key
    dest: /etc/ssl/private/
    owner: root
    group: root
    mode: "0600"
  notify: Restart nginx
