---
- name: Restart zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: true

- name: Restart zabbix-server
  ansible.builtin.service:
    name: zabbix-server
    state: restarted
    enabled: true
