---
- name: "Check port 22"
  wait_for:
    port: "22"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "3"
    timeout: "3"
  delegate_to: "localhost"
  ignore_errors: "yes"
  register: ssh_port

- name: Set SSH port to 22
  set_fact:
    ansible_port: "22"
  when: ssh_port is success

- name: Set SSH port to 51000
  set_fact:
    ansible_port: "51000"
  when: ssh_port is failed
