---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ role_name }}"

- name: Installation of isc-dhcp-server
  ansible.builtin.apt:
    pkg:
    - isc-dhcp-server

- name: Installation of dhcpd.conf
  ansible.builtin.copy:
    src: dhcpd.conf
    dest: /etc/dhcp/
    owner: root
    group: root
    mode: '0644'
  notify: Restart isc-dhcp-server
