---
- name: Download the GLPI latest release
  ansible.builtin.get_url:
    url: https://github.com/glpi-project/glpi/releases/download/{{ glpi_version }}/glpi-{{ glpi_version }}.tgz
    dest: /tmp

- name: Extract glpi.tgz into /srv/glpi
  ansible.builtin.unarchive:
    src: /tmp/glpi-{{ glpi_version }}.tgz
    dest: /srv/
    remote_src: true
    owner: www-data
    group: www-data
    mode: "0755"

- name: Installation of required PHP packages
  ansible.builtin.apt:
    pkg:
    - php-fpm
    - php-common
    - php{{ php_version }}-common
    - php-mysql
    - php-json
    - php-curl
    - php-gd
    - php-intl
    - php-ldap
    - php-bz2
    - php-zip
    - php-mbstring
    - php-xml

- name: Start and enable the php-fpm service
  ansible.builtin.service:
    name: php{{ php_version }}-fpm
    state: started
    enabled: true

- name: Installation of the glpi configuration
  ansible.builtin.template:
    src: ../templates/glpi.j2
    dest: /etc/nginx/sites-available/glpi
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx

- name: Activation of the GLPI website
  ansible.builtin.file:
    src: /etc/nginx/sites-available/glpi
    dest: /etc/nginx/sites-enabled/glpi
    owner: root
    group: root
    state: link
  notify: Reload nginx

- name: Add the TLS cert for GLPI
  ansible.builtin.copy:
    src: ../secrets/glpi.exo-industries.xyz.crt
    dest: /etc/ssl/certs/glpi.exo-industries.xyz.crt
    owner: root
    group: root
    mode: "0640"
  notify:
    - Restart nginx

- name: Add the TLS key for GLPI
  ansible.builtin.copy:
    src: ../secrets/glpi.exo-industries.xyz.key
    dest: /etc/ssl/private/glpi.exo-industries.xyz.key
    owner: root
    group: root
    mode: "0600"
  notify:
    - Restart nginx

- name: Add the new nginx user in the www pool
  ansible.builtin.replace:
    path: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
    regexp: 'www-data'
    replace: "{{ nginx_user }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart php-fpm

- name: Add the hardening php.ini file
  ansible.builtin.copy:
    src: ../templates/php.ini.j2
    dest: /etc/php/{{ php_version }}/fpm/php.ini
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart php-fpm

- name: Create the database
  mysql_db:
    name: "{{ glpi_db }}"
    login_host: 192.168.10.230
    state: present

- name: Create database user and password with all database privileges
  mysql_user:
    name: "{{ glpi_dbuser }}"
    password: "{{ glpi_dbpasswd }}"
    priv: '*.*:ALL'
    login_host: 192.168.10.230
    state: present
