---
- name: Download the GLPI latest release
  ansible.builtin.get_url:
    url: https://github.com/glpi-project/glpi/releases/download/{{ glpi_version }}/glpi-{{ glpi_version }}.tgz
    dest: "/srv/"

- name: Extract glpi.tgz into /srv/glpi
  ansible.builtin.unarchive:
    src: /srv/glpi-{{ glpi_version }}.tgz
    dest: /srv/glpi
    remote_src: yes
