---
- name: Download the GLPI latest release
  ansible.builtin.get_url:
    url: https://github.com/glpi-project/glpi/releases/download/{{ glpi_version }}/glpi-{{ glpi_version }}.tgz
    dest: /tmp

- name: Extract glpi.tgz into /srv/glpi
  ansible.builtin.unarchive:
    src: /tmp/glpi-{{ glpi_version }}.tgz
    dest: /srv/
    remote_src: true
    owner: www-data
    group: www-data
    mode: "0755"

- name: Installation of required packages
  ansible.builtin.apt:
    pkg:
    - mariadb-server
    - php-fpm
    - php-common
    - php-mysql
    - php-json
    - php-curl
    - php-gd
    - php-intl
    - php-ldap
    - php-bz2
    - php-zip
    - php-mbstring

- name: Hardening of GLPI permissions
  ansible.builtin.file:
    path: /srv/glpi/public
    state: directory
    mode: '0750'

- name: Start and enable the php-fpm service
  ansible.builtin.service:
    name: php{{ php_version }}-fpm
    state: started
    enabled: true

- name: Start and enable the mariadb service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Installation of the glpi configuration
  ansible.builtin.template:
    src: ../templates/glpi.j2
    dest: /etc/nginx/sites-available/glpi
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx

- name: Activation of the GLPI website
  ansible.builtin.file:
    src: /etc/nginx/sites-available/glpi
    dest: /etc/nginx/sites-enabled/glpi
    owner: root
    group: root
    state: link
  notify: Reload nginx

- name: Add the TLS cert for GLPI
  ansible.builtin.copy:
    src: ../secrets/glpi.exo-industries.xyz.crt
    dest: /etc/ssl/certs/glpi.exo-industries.xyz.crt
    owner: root
    group: root
    mode: "0640"
  notify:
    - Restart nginx

- name: Add the TLS key for GLPI
  ansible.builtin.copy:
    src: ../secrets/glpi.exo-industries.xyz.key
    dest: /etc/ssl/private/glpi.exo-industries.xyz.key
    owner: root
    group: root
    mode: "0600"
  notify:
    - Restart nginx

- name: Add the hardening php.ini file
  ansible.builtin.copy:
    owner: root
    group: root
    mode: "0644"
  with_items:
   - { src: ../templates/php.ini.j2, dest: /etc/php/{{ php_version }}/cli/}
   - { src: ../templates/php.ini.j2, dest: /etc/php/{{ php_version }}/fpm/}
  notify:
    - Restart php-fpm
