---
- name: Restart mariadb
  ansible.builtin.service:
    name: mariadb
    state: restarted
    enabled: true

- name: Reload mariadb
  ansible.builtin.service:
    name: mariadb
    state: reloaded
    enabled: true
