---
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
    enabled: true

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
