---
- name: Installation of bind9 and prometheus-bind-exporter
  ansible.builtin.apt:
    pkg:
    - bind9
    - bind9-utils
    - prometheus-bind-exporter

- name: Installation of db.10.168.192.in-addr.arpa
  ansible.builtin.copy:
    src: db.10.168.192.in-addr.arpa
    dest: /etc/bind/
    owner: root
    group: bind
    mode: '0640'
  notify:
    - Restart bind9

- name: Installation of db.exo-industries.xyz
  ansible.builtin.copy:
    src: db.exo-industries.xyz
    dest: /etc/bind/
    owner: root
    group: bind
    mode: '0640'
  notify:
    - Restart bind9

- name: Installation of named.conf.local
  ansible.builtin.copy:
    src: named.conf.local
    dest: /etc/bind/
    owner: root
    group: bind
    mode: '0640'
  notify:
    - Restart bind9

- name: Installation of named.conf.options
  ansible.builtin.copy:
    src: named.conf.options
    dest: /etc/bind/
    owner: root
    group: bind
    mode: '0640'
  notify:
    - Restart bind9

- name: Installation of TSIG key
  ansible.builtin.copy:
    src: dns1-dns2.key
    dest: /etc/bind/
    owner: root
    group: bind
    mode: '0640'
  notify:
    - Restart bind9
