---
- name: Installation of bind9
  ansible.builtin.apt:
    pkg:
    - bind9
    - bind9-utils

- name: Create the dev folder
  ansible.builtin.file:
    path: /var/lib/bind/dev
    state: directory
    owner: root
    group: bind
    mode: '0750'

- name: Create the etc folder
  ansible.builtin.file:
    path: /var/lib/bind/etc
    state: directory
    owner: root
    group: bind
    mode: '0750'

- name: Create the run/named folder
  ansible.builtin.file:
    path: /var/lib/bind/var/run/named
    state: directory
    owner: root
    group: bind
    mode: '0750'

- name: Create the cache folder
  ansible.builtin.file:
    path: /var/lib/bind/var/cache/bind
    state: directory
    owner: root
    group: bind
    mode: '0750'

- name: Create the null device file
  ansible.builtin.command:
    cmd: mknod /var/lib/bind/dev/null c 1 3 2> /dev/null || true

- name: Apply rights for the special null device file
  ansible.builtin.file:
    path: /var/lib/bind/dev/null
    owner: root
    group: root
    mode: '0666'

- name: Create the random device file
  ansible.builtin.command:
    cmd: mknod /var/lib/bind/dev/random c 1 8 2> /dev/null || true

- name: Apply rights for the special random device file
  ansible.builtin.file:
    path: /var/lib/bind/dev/random
    owner: root
    group: root
    mode: '0666'

- name: Installation of db.10.168.192.in-addr.arpa
  ansible.builtin.template:
    src: ../templates/db.10.168.192.in-addr.arpa.j2
    dest: /var/lib/bind/etc/bind/db.10.168.192.in-addr.arpa
    owner: root
    group: bind
    mode: '0640'
  notify:
    - Restart bind9

- name: Installation of db.exo-industries.xyz
  ansible.builtin.template:
    src: ../templates/db.exo-industries.xyz.j2
    dest: /var/lib/bind/etc/bind/db.exo-industries.xyz
    owner: root
    group: bind
    mode: '0640'
  notify:
    - Restart bind9

- name: Installation of named.conf.local
  ansible.builtin.template:
    src: ../secrets/named.conf.local.j2
    dest: /var/lib/bind/etc/bind/named.conf.local
    owner: root
    group: bind
    mode: '0640'
  notify:
    - Restart bind9

- name: Installation of named.conf.options
  ansible.builtin.template:
    src: ../templates/named.conf.options.j2
    dest: /var/lib/bind/etc/bind/named.conf.options
    owner: root
    group: bind
    mode: '0640'
  notify:
    - Restart bind9

- name: Installation of TSIG key
  ansible.builtin.template:
    src: ../secrets/dns1-dns2.key
    dest: /var/lib/bind/etc/bind/
    owner: root
    group: bind
    mode: '0640'
  notify:
    - Restart bind9

- name: Copy all files in the chroot directory
  ansible.builtin.copy:
    src: /etc/bind/*
    dest: /var/lib/bind/etc/bind/
    owner: root
    group: bind
    mode: '0640'
  notify:
    - Restart bind9
