---
- name: Installation of the prometheus configuration
  ansible.builtin.copy:
    src: prometheus
    dest: /etc/nginx/sites-available/
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx

- name: Activation of the prometheus website
  ansible.builtin.file:
    src: /etc/nginx/sites-available/prometheus
    dest: /etc/nginx/sites-enabled/prometheus
    owner: root
    group: root
    state: link
  notify: Reload nginx

- name: Add the TLS cert for prometheus
  ansible.builtin.copy:
    src: prometheus.exo-industries.xyz.crt
    dest: /etc/ssl/certs/
    owner: root
    group: root
    mode: "0640"
  notify: Restart nginx

- name: Add the TLS key for prometheus
  ansible.builtin.copy:
    src: prometheus.exo-industries.xyz.key
    dest: /etc/ssl/private/
    owner: root
    group: root
    mode: "0600"
  notify: Restart nginx
